### ISSUE TITLE
[New] plugin.image.daily_dilbert

### ISSUE THREAD

**Issue by bigcookie** [xbmc/repo-plugins#1109]
### Add-on details:
New Dilbert comic strip plugin for pictures section. It allows to access daily Dilbert, but also recents, random, browsing by date and entering a date. It is based on the old (not anymore working) plugin.image.dibert and (still working) plugin.image.garfield_comic.
The plugin allows you to principally select dates and on selection it will scrape the Dilbert webpage for the URL to show and displays the comic strip. It is tested on Jarvis and Krypton
This is my first Python and Plugin work and I am not a trained programmer. Any comments are welcome, but remember you are talking to a untrained programmer...

- Add-on name: Daily Dilbert
  - Add-on ID: plugin.image.daily_dilbert
  - Version number: 1.1.2
  - Kodi/repository version: Krypton
- URL: https://github.com/bigcookie/plugin.image.daily_dilbert
  - Revision/tag: v1.1.2
  - Branch: Release_v1.x

### Description of changes:
New addon to access online Dilbert comic strips. Following features provided:
- Daily Dilbert access
- Recent Dilberts access
- Random Dilberts
- Browse by Date
- Enter specific date

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Questions:
1. The plugin is tested on Jarvis and Krypton, but as it is a new plugin, I can only release it to Krypton, right? So I put Krypton above. If I can push to Jarvis, please change to Jarvis.
2. Coding guidelines: With the link below, I couldnt find the description. Please help me to understand them, if my code is not compliant. Sorry for the inconvenience

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by Razzeee** [comment]
Can you change summary and description from "en" to "en_GB" in the addon.xml

**Comment by Razzeee** [comment]
On a related not, you might want to add a git ignore and remove all `.pyo` files.

Just create a file named `.gitignore` and fill it with something like this https://github.com/xbmc/generator-kodi-addon/blob/master/generators/app/templates/gitignore

**Comment by Razzeee** [comment]
You've also have icon.png and fanart.png twice. And it seems like the ones under `resources` doesn't seem to be used.

**Comment by Razzeee** [comment]
You can also add <import addon="script.module.t0mm0.common" version="2.1.1"/> here 
https://github.com/bigcookie/plugin.image.daily_dilbert/blob/master/plugin.image.daily_dilbert/addon.xml#L4
Then you should be able to remove the modules folder here (you might have to change the import slightly) https://github.com/bigcookie/plugin.image.daily_dilbert/tree/master/plugin.image.daily_dilbert/resources/lib/modules

Or as I'm seeing you want to get rid of that module I would stongly suggest that you use this instead:
https://github.com/tamland/kodi-plugin-routing
You can add it to the addon.xml just like the one above.

**Comment by bigcookie** [comment]
Will change en to en_GB in addon.xml (actually done, still need to push)

Regarding icon.png and fanart.jpg: I read, that the location changed in KRypton and following to the resources folder, but I was unsure and tested also on Jarvis prior. Can you confirm, that I can remove icon.png and fanart.jpg from the resources folder and leave it in plugin-root (Wiki says "resources" folder as I read it)? My Kodi somehow cached them and I am not sure how to remove the cache and properly test which location is the correct one.

Regarding import and pyo. As I understand, I can leave it as it is for now, but a change would be recommended. As I need to check and test more due to my missing knowledge, I would like to leave it as it is for now and change later. Is this acceptable?
The same goes for the usage of your recommended module.

Thanks for your helping comments!

Last question: After the changes, I will assign a new tag and update the ticket, or what is the preferred procedure?

Thanks, regards

**Comment by Razzeee** [comment]
You can either:
- remove the ones under resources
- go for the new handling and remove the ones in the top level then edit your `addon.xml` see: http://kodi.wiki/view/Addon.xml#.3Cassets.3E

You will have to do the part about the gitignore and removing the pyo, otherwise whoever does the Pull Request for you will have to do that.

The import part is not exactly a problem, but it generates work on our end as we need to review a file your not really using and we already have a reviewed version of in our repo. Maybe I can find some time and send you a PR tonight.

Yes, update the tag and ticket and write a comment that you did update it.

**Comment by bigcookie** [comment]
Following changes done in code:
- replaced "en" with "en_GB" in addon.xml
- version number pushed to 1.0.1 in addon.xml
- removed all .pyo files
- removed fanart.jpg and icon.png in resources folder

Changes in repo:
- added tag v1.0.1
- created .gitignore

Changes in ticket:
- updated tag version to be pulled
- updated plugin version 

The switching of the imported module to your recommended one I cannot do quickly due to time (need to understand all of this better). If this is sufficient to do the pull, I would be glad. The file addon.py under /lib/modules/ was already used by the garfield_comic plugin - I just copied it. Perhaps this makes the review easier.

Thanks a lot for the help!

**Comment by MartijnKaijser** [comment]
@Razzeee our git has pyo (and other files) hidden by default so it should never be added auto  when doing a PR

**Comment by Razzeee** [comment]
@bigcookie 
What I normally do:
- clone the repo-plugins repo
- make sure you switch your local to the correct minimal target branch, probably krypton for this as it's a new addon
- if your my addon is already in the repo I'll now delete the folder from the repo-plugins folder
- I now copy my new version into the repo-plugins folder 
- (you might have to remove the `.git` folder inside your addons folder now)
- commit the whole repo with the `[addon.name] version` commit message and create a new branch when you do this
- push it
- go to the repo on github and you should be able to create a PR

**Comment by Razzeee** [comment]
Btw have you tested your addon with estuary? It doesn't seem to work for me, it seems fine in confluence.

@phil65 you might be interested

**Comment by bigcookie** [comment]
Hi, I havent (simply forgot that the standard skin changed). But even in Estuary, my movie section is completely empty. Series work though.
In picture section I dont see any of the 4 installed addons. Under Addons they are listed though...
Debug log shows, the script was run successfully. Nothing more yet...

**Comment by Razzeee** [comment]
Let me know if you find something. I will start looking this evening, if I find some time.

**Comment by bigcookie** [comment]
I will check details. Most likely it is connected to the old addon.py module as the Garfield plugin also doesnt work. 
I might also want to setup an IDE as I am now developing with notepad++ ;-) (as said: not a developer). Sorry for the inconvenience, but I learned a lot - also thanks for the PR help. I read the commandline howto on the Wiki, but instead of copying that I wanted to properly understand it. Thanks for this!

My proposal for now:
- follow-up with the estuary issue. I think my movie issues are coming from my MySQL configuration as I switch from working environment with distributed database to local one. 
- I will check the issue in the plugin with estuary.

Unfortunately my time is limited for this work, but I will update asap when I found anything.

**Comment by bigcookie** [comment]
I suggest to stop this PR now. I will remove the addon.py module and change the code to directly follow this tutorial:
http://kodi.wiki/view/Audio/video_add-on_tutorial
Thus it should become simpler code, old code gets removed, review is simplified (i saw, you already checked addon.py... Sorry)
I will update this thread when done. Please note, that I might not be able to do this before before week.

**Comment by Razzeee** [comment]
You might also want to look at this https://github.com/xbmc/generator-kodi-addon

**Comment by bigcookie** [comment]
Update on estuary issue:
- I switched to the internal t0mm0 module (<import addon="script.module.t0mm0.common" version="2.1.1"/>) thanks to Razzeee -> Plugin works under confluence, but not under estuary. Nothing is shown. When I switched to another plugin "Cooking with Kodi" the main page from my plugin shortly showed up and was then updated with the new plugin menu (happened only once)
Using "Debug log" in Kodi didnt show anything special. Here is the extract - according to the log, all seems to be fine to me. As the snipped is short, I paste it here - hope this is ok.

Additionally the Picture folder didnt show any of the installed 4 Plugins, only my linked Picture directory.
-> Let me know, if this is worth to create a bug report. I think this should not be part of this "thread".

T:4784   DEBUG: CDirectoryProvider[addons://sources/image/]: refreshing..
21:01:17.620 T:4784   DEBUG: Keyboard: scancode: 0x01, sym: 0x001b, unicode: 0x0000, modifier: 0x0
21:01:18.616 T:4784   DEBUG: Keyboard: scancode: 0x4d, sym: 0x0113, unicode: 0x0000, modifier: 0x0
21:01:18.616 T:4784   DEBUG: CInputManager::OnKey: right (0xf083) pressed, action is Right
21:01:18.767 T:4784   DEBUG: Keyboard: scancode: 0x4d, sym: 0x0113, unicode: 0x0000, modifier: 0x0
21:01:18.950 T:4784   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
21:01:19.100 T:4784   DEBUG: CInputManager::OnKey: return (0xf00d) pressed, action is Select
21:01:19.100 T:4784   DEBUG: Activating window ID: 10002
21:01:19.405 T:4784   DEBUG: ------ Window Deinit (Home.xml) ------
21:01:19.446 T:4784   DEBUG: ------ Window Init (MyPics.xml) ------
21:01:19.454 T:4784   ERROR: Control 55 in window 10002 has been asked to focus, but it can't
21:01:19.454 T:4784   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
21:01:19.456 T:4784   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.image.daily_dilbert/)
21:01:19.456 T:4784   DEBUG:   ParentPath = [plugin://plugin.image.daily_dilbert/]
21:01:19.489 T:12084   DEBUG: CAddonDatabase::SetLastUsed[plugin.image.daily_dilbert] took 34 ms
21:01:19.489 T:9088   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin Daily Dilbert('plugin://plugin.image.daily_dilbert/','3','')
21:01:19.490 T:1580   DEBUG: Thread LanguageInvoker start, auto delete: false
21:01:19.491 T:1580    INFO: initializing python engine.
21:01:19.491 T:1580   DEBUG: CPythonInvoker(9, C:\Users\andrkuhn\AppData\Roaming\Kodi\addons\plugin.image.daily_dilbert\addon.py): start processing
21:01:19.537 T:1580   DEBUG: -->Python Interpreter Initialized<--
21:01:19.537 T:1580   DEBUG: CPythonInvoker(9, C:\Users\andrkuhn\AppData\Roaming\Kodi\addons\plugin.image.daily_dilbert\addon.py): the source file to load is "C:\Users\andrkuhn\AppData\Roaming\Kodi\addons\plugin.image.daily_dilbert\addon.py"
21:01:19.538 T:1580   DEBUG: CPythonInvoker(9, C:\Users\andrkuhn\AppData\Roaming\Kodi\addons\plugin.image.daily_dilbert\addon.py): setting the Python path to C:\Users\andrkuhn\AppData\Roaming\Kodi\addons\plugin.image.daily_dilbert;C:\Users\andrkuhn\AppData\Roaming\Kodi\addons\script.module.t0mm0.common\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
21:01:19.538 T:1580   DEBUG: CPythonInvoker(9, C:\Users\andrkuhn\AppData\Roaming\Kodi\addons\plugin.image.daily_dilbert\addon.py): entering source directory C:\Users\andrkuhn\AppData\Roaming\Kodi\addons\plugin.image.daily_dilbert
21:01:19.538 T:1580   DEBUG: CPythonInvoker(9, C:\Users\andrkuhn\AppData\Roaming\Kodi\addons\plugin.image.daily_dilbert\addon.py): instantiating addon using automatically obtained id of "plugin.image.daily_dilbert" dependent on version 2.25.0 of the xbmc.python api
21:01:19.956 T:4784   DEBUG: ------ Window Init (DialogBusy.xml) ------
21:01:19.958 T:1580   DEBUG: Daily Dilbert: adding item: Today's Dilbert - plugin://plugin.image.daily_dilbert/?mode=today
21:01:19.959 T:1580   DEBUG: Daily Dilbert: adding item: Recent Dilberts - plugin://plugin.image.daily_dilbert/?mode=last_week&page=1
21:01:19.971 T:1580   DEBUG: Daily Dilbert: adding item: Random Dilbert - plugin://plugin.image.daily_dilbert/?mode=random
21:01:19.972 T:1580   DEBUG: Daily Dilbert: adding item: Browse dates - plugin://plugin.image.daily_dilbert/?mode=browse&page=1
21:01:19.972 T:1580   DEBUG: Daily Dilbert: adding item: Open a specific date - plugin://plugin.image.daily_dilbert/?mode=enter
21:01:19.972 T:1580    INFO: CPythonInvoker(9, C:\Users\andrkuhn\AppData\Roaming\Kodi\addons\plugin.image.daily_dilbert\addon.py): script successfully run
21:01:20.006 T:11336   DEBUG: Thread BackgroundLoader start, auto delete: false
21:01:20.010 T:11336   DEBUG: Thread BackgroundLoader 11336 terminating
21:01:20.011 T:4784   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
21:01:20.017 T:1580    INFO: Python script stopped
21:01:20.017 T:1580   DEBUG: Thread LanguageInvoker 1580 terminating
21:01:22.117 T:4784   DEBUG: Keyboard: scancode: 0x01, sym: 0x001b, unicode: 0x001b, modifier: 0x0
21:01:22.269 T:4784   DEBUG: CInputManager::OnKey: escape (0xf01b) pressed, action is PreviousMenu
21:01:22.269 T:4784   DEBUG: CGUIWindowManager::PreviousWindow: Deactivate
21:01:22.572 T:4784   DEBUG: ------ Window Deinit (MyPics.xml) ------
21:01:22.584 T:4784   DEBUG: CGUIWindowManager::PreviousWindow: Activate new
21:01:22.584 T:4784   DEBUG: ------ Window Init (Home.xml) ------
21:01:22.584 T:4784   DEBUG: CDirectoryProvider[addons://sources/video/]: refreshing..
21:01:22.584 T:4784   DEBUG: CDirectoryProvider[addons://sources/audio/]: refreshing..
21:01:22.584 T:4784   DEBUG: CDirectoryProvider[addons://sources/executable/]: refreshing..
21:01:22.584 T:4784   DEBUG: CDirectoryProvider[addons://sources/image/]: refreshing..
21:01:22.593 T:4784   DEBUG: Keyboard: scancode: 0x01, sym: 0x001b, unicode: 0x0000, modifier: 0x0
21:01:23.068 T:4784   DEBUG: Keyboard: scancode: 0x48, sym: 0x0111, unicode: 0x0000, modifier: 0x0
21:01:23.068 T:4784   DEBUG: CInputManager::OnKey: up (0xf080) pressed, action is Up
21:01:23.168 T:4784   DEBUG: Keyboard: scancode: 0x48, sym: 0x0111, unicode: 0x0000, modifier: 0x0

**Comment by Razzeee** [comment]
Doesn't seem to be a bug, setContent for estuary is stricter when it comes to types. And it seems like your using one, that's simply not valid in the eyes of the skin.
Here's the documentation with some that are valid, unfortunatly there's none for pictures.
http://mirrors.xbmc.org/docs/python-docs/stable/xbmcplugin.html#-setContent

Just remove https://github.com/bigcookie/plugin.image.daily_dilbert/blob/master/plugin.image.daily_dilbert/addon.py#L269 and it will start to work

**Comment by bigcookie** [comment]
Ok, now learning a lot (thanks @Razzeee ), I removed the module, updated the plugin and fixed an issue with the random strip display by introducing a cache. The Plugin is tested now under Krypton Confluence AND Estuary.
Please help creating the PR now.

**Comment by Tadly** [comment]
Got two more changes to request:
 1. [Should be en_GB as well](https://github.com/bigcookie/plugin.image.daily_dilbert/blob/master/plugin.image.daily_dilbert/addon.xml#L12)
 2. [Should be tabs, not spaces](https://github.com/bigcookie/plugin.image.daily_dilbert/blob/master/plugin.image.daily_dilbert/addon.py#L149-L151) (Python relies heavily on indentation and mixing is always bad. In this case it would work but is bad practices)

After that I think we're good to go

**Comment by bigcookie** [comment]
Updated with latest requested changes from tadly in the pull request. 
Changed tag to be committed to "v1.1.1". 
@Razzeee: Thanks for creating the PR. I understood now how to create one based on your description, but I dont want to mess up the current PR as the commit was done by you. May I ask you to update the PR? If not, I am happy to go forward.

**Comment by bigcookie** [comment]
Updated with latest requested changes from enen92 in the pull request.
Changed tag to be committed to "v1.1.2".
@Razzeee: Can you update the files again? Sorry for the incovenience. Next PR I can then do on my own.

**Comment by MartijnKaijser** [comment]
addon was added
