### ISSUE TITLE
[Update] plugin.video.noco

### ISSUE THREAD

**Issue by gormux** [xbmc/repo-plugins#1191]
### Add-on details:

- **General**
  - Add-on name: plugin.video.noco
  - Add-on ID: 
  - Version number: 1.0.12
  - Kodi/repository version: all

- **Code location**
  - URL: http://dev.gormotte.info/plugin.video.noco/
  - Revision/tag: 9b9f0b366c87
  - Branch: default

### Description of changes:

Added support for playlists / queuing, thanks to pcjco

### Checklist:

- [ X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
This is probably the last update if nothing breaks the plugin in a future release, as it works correctly and has apparently all the features people want (as I only received this contribution in the last... 2 years iirc, no plugin-related bugs or feature requests), so as I'm not used to git (and had difficulties contributing to ansible recently), I did not take the time to use a PR for this update.

**Comment by eracknaphobia** [comment]
I've created a pull request for you. A reviewer will be by shortly, please fix any changes requested. Once you've made these changes let me know and I will update your pull request. Thanks for submitting to our repo!

**Comment by gormux** [comment]
Hello,

The contributor added changes, I asked him to make a PR himself on github yesterday.
But if things have changed on the plugins since I updated, maybe it is a good idea to make this first PR on github, so he can make PRs after this update.

Thanks

**Comment by eracknaphobia** [comment]
I am closing this issue as the pull request has been merged successfully. Thanks for contributing!
