### ISSUE TITLE
[Update] plugin.audio.ramfm

### ISSUE THREAD

**Issue by spoyser** [xbmc/repo-plugins#1375]
- Add-on name: RAM FM Radio Addon
  - Add-on ID: plugin.audio.ramfm
  - Version number: 2.0.6
  - Kodi/repository version: Krypton
  - URL: https://drive.google.com/file/d/0B8CEI9txoUlWZ3pBR3J3UGVBRFE/view?usp=sharing

### Description of changes:
 - Added 320kbps stream

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by learningit** [comment]
Can you submit via github? PITA to do a diff otherwise. Would be much faster to approve.

**Comment by Razzeee** [comment]
I've created a PR for you
