### ISSUE TITLE
Add Addon Fusion

### ISSUE THREAD

**Issue by jesusosx** [xbmc/repo-plugins#1410]
### Add-on details:

- **General**
  - Add-on name: Fusion
  - Add-on ID: plugin.video.fusion
  - Version number: 1.0.0
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/jesusosx/fusion/tree/master/plugin.video.fusion
  - Revision/tag: 623f9b3
  - Branch: master

### Checklist:

- [X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by learningit** [comment]
We do not accept piracy addons.
