### ISSUE TITLE
App Tidal in music provider is broke

### ISSUE THREAD

**Issue by ghost** [xbmc/repo-plugins#1417]
I see that the app TIDAL distributed by the oficial kodi repository has been broken for ages, there is a new app named tidal2 that has taken over. please mark the tidal app as broken

**Comment by Razzeee** [comment]
Tidal2 isn't in the official repo, it that correct?

**Comment by MartijnKaijser** [comment]
https://kodi.tv/addon/music-add-ons-plugins/tidal

@tamland ping
