### ISSUE TITLE
Commit Add-on to 17.x branch

### ISSUE THREAD

**Issue by vdineshd** [xbmc/repo-plugins#1418]
[Update] plugin.Add-on.Kodi

### Add-on details:
  - Add-on name: CTA
  - Add-on ID: 
  - Version number: 2.0
  - Kodi/repository version: 17.x
  - URL: 
  - Revision/tag: 2.0
  - Branch: master

### Checklist:
-- I haven't gone through it yet but I wanted to know how can I do my add-on commit on 17.x kodi?
What are the steps?
I am creating this issue to request help on the same.

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
this issue is missing all relevant information, like addon id and url.
we can not process this request as-is.

please provide the necessary info.

**Comment by vdineshd** [comment]
I know it is less information. But I have mentioned that I need steps how I need to do it and do i need to commit code or just binary of add-on is good enough?

The add-on which I want to add in repository of 17.x belongs from my company so I am not in position to share it with out having all clear information.
So requesting you to provide brief information and yes this is for the first time i am going to do so asking.
Please do the needful.

**Comment by learningit** [comment]
Read this first:
http://kodi.wiki/view/Submitting_Add-ons#Github

**Comment by Razzeee** [comment]
Going to close this for now. Feel free to still talk in here.
