### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Dagur** [xbmc/repo-plugins#1429]
Hi, I hope it's OK to post questions here.

I'm going to create a pull request for a plugin I made a long time ago. It's in the Gotham branch but not any of the newer ones. 
Do I just commit my changes to Gotham or should I commit to all the stable branches above it as well?

**Comment by Razzeee** [comment]
Gotham is end of life, we will not accept that

**Comment by Dagur** [comment]
Are you sure? According to this http://kodi.wiki/view/Submitting_Add-ons  you accept updates

**Comment by Razzeee** [comment]
Sorry, I think I read your intial post wrong. Like it's not yet in the gotham branch and you will try to add it to there. If it already is in there and you want to update it, that's okay.
https://github.com/xbmc/repo-plugins/tree/gotham#status
