### ISSUE TITLE
[plugin.video.ecbtv] Unable to install

### ISSUE THREAD

**Issue by LS80** [xbmc/repo-plugins#1527]
https://github.com/xbmc/repo-plugins/pull/1525 was merged before the dependent PR https://github.com/xbmc/repo-scripts/pull/678. This means that the `plugin.video.ecbtv` 0.6.0 update cannot be installed, due to a missing dependency.

This can be fixed by merging https://github.com/xbmc/repo-scripts/pull/678.

**Comment by MartijnKaijser** [comment]
done
