### ISSUE TITLE
[New] plugin.video.category5

### ISSUE THREAD

**Issue by Cat5TV** [xbmc/repo-plugins#1592]
### Add-on details:

- **General**
  - Add-on name: Category5.TV
  - Add-on ID: plugin.video.category5
  - Version number: 1.1.4
  - Kodi/repository version: 12/Frodo+

- **Code location**
  - URL: https://github.com/Cat5TV/plugin.video.category5
  - Revision/tag: 9df2421
  - Branch: master

### Description of changes:

This is a new submission, tested to work on both legacy and modern versions of Kodi. The channel and the content within it are created by us (Category5 TV Network) and provided free of charge to all. Unless otherwise noted, video is CC BY-NC-SA 3.0. I hope Kodi users enjoy the content.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by MartijnKaijser** [comment]
@Cat5TV would it be possible to submit the plugin through a pull request? We'll make sure to help you get through it.
Here's some starting info
https://kodi.wiki/view/Submitting_Add-ons#Pull_requests

**Comment by Cat5TV** [comment]
Yeah I'd love to - I just didn't want to mess it up, so thought it best to let folks who had done it before do the PR  :)  I will see if I can work through the steps. Thanks  :)

**Comment by MartijnKaijser** [comment]
Don't be afraid to mess up  :)

**Comment by Cat5TV** [comment]
LOL - Well, ideally, the things we do shouldn't break Kodi :p More like, I'd want to make sure it works! haha

**Comment by Cat5TV** [comment]
Looks like this would be the way to go? https://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging

**Comment by MartijnKaijser** [comment]
yep.

**Comment by Cat5TV** [comment]
Alright cool. Easy enough. I'll try to do this this weekend. Thanks  :)

**Comment by MartijnKaijser** [comment]
sorry for not responding sooner :)

**Comment by Cat5TV** [comment]
Hey ... don't apologize. If you want to talk about tardy behavior, we've been broadcasting for 11 years. We have had a Kodi plugin for 3 years... and I'm just now figuring out how to make it "official"  :D
