### ISSUE TITLE
Permission to xbmc/repo-plugins.git denied to known-as-bmf

### ISSUE THREAD

**Issue by known-as-bmf** [xbmc/repo-plugins#1704]
Hello, 

I am the owner of [plugin.video.arteplussept](https://github.com/known-as-bmf/plugin.video.arteplussept).

 I tried following the steps described in [this guide](https://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging) to update the plugin, but the last step (`git push origin gotham`) gives me the following error :

```
remote: Permission to xbmc/repo-plugins.git denied to known-as-bmf.
fatal: unable to access 'https://github.com/xbmc/repo-plugins.git/': The requested URL returned error: 403
```

Do I need some kind of permission to push to this repo ?

Best regards,
Julien

**Comment by MartijnKaijser** [comment]
You first need to fork our Repo to your Repo and then push there. After that you can create a pull request to the correct branch

**Comment by known-as-bmf** [comment]
Here are the steps I followed

```
$ git clone https://github.com/xbmc/repo-plugins.git
$ cd repo-plugins/
$ git checkout gotham
$ git remote add arteplussept https://github.com/known-as-bmf/plugin.video.arteplussept.git
$ git fetch arteplussept
$ git checkout -b arteplussept_branch arteplussept/master
$ git checkout gotham
$ git rm -r plugin.video.arteplussept/
$ git read-tree --prefix=plugin.video.arteplussept/ -u arteplussept_branch
$ git commit -m "[plugin.video.arteplussept] 0.5.8"
$ git push origin gotham
```

Did I miss something ?

**Comment by MartijnKaijser** [comment]
yes, you need to hit the fork button github page and clone that which should end up like 

$ git clone https://github.com/known-as-bmf/repo-plugins.git

**Comment by known-as-bmf** [comment]
Ok, I am dumb, I cloned https://github.com/xbmc/repo-plugins.git instead of my fork of it.

**Comment by MartijnKaijser** [comment]
small difference :)

**Comment by known-as-bmf** [comment]
Thank you for your time, I am sorry about that.

**Comment by MartijnKaijser** [comment]
no problem
