### ISSUE TITLE
[NEW] plugin.video.specialfeatures 3.0.0 

### ISSUE THREAD

**Issue by smitchell6879** [xbmc/repo-plugins#1730]
### Add-on details:
- **General**
  - Add-on name:  Special Features
  - Add-on ID: plugin.video.specialfeatures
  - Version number: 3.0.0
  - Kodi/repository version: 17 & 18

- **Code location**
  - URL: https://github.com/smitchell6879/plugin.video.specialfeatures/tree/master
  - Release URL : https://github.com/smitchell6879/plugin.video.specialfeatures/releases/tag/3.0.0
  - Wiki URL :https://kodi.wiki/view/Add-on:Special_Features
  - Forum URL: https://forum.kodi.tv/showthread.php?tid=327042
  - Revision/tag: 3.0.0
  - Branch: master

### Description of changes:
Given a properly structured 'Extras' directory, this addon will present all of the bonus media in your library. 

Note: I attempted two pull request one creating my own branch and another directly to krypton but bother fail due to invalid permissions and since I am new to the whole process figured this would be the next attempt.

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by smitchell6879** [comment]
So do you want it in its own new module or actually add it into myconnpy?

**Comment by smitchell6879** [comment]
Alirght  I will update you once I get time to put it together then we can try it again

**Comment by smitchell6879** [comment]
I have removed pymysql. Submitted it as a new module and updated current version still using the same tag 3.0.0 with a new updated release.

**Comment by Lunatixz** [comment]
Moved to PR https://github.com/xbmc/repo-plugins/issues/1730
