### ISSUE TITLE
[Delete] plugin.video.btsportvideo

### ISSUE THREAD

**Issue by LS80** [xbmc/repo-plugins#1891]
### Add-on details:

- **General**
  - Add-on name: BT Sport Video
  - Add-on ID: plugin.video.btsportvideo
  - Version number: 0.3.0
  - Kodi/repository version: Krypton

BT Sport have asked for the add-on to be removed.

>  We want to ensure the best experience for our customers via services like our Enhanced player which gives live match statistics, multi-camera action replays and virtual reality options. This means that we need to ensure that our customers are using our approved and tested applications.

> However, as BT does not make the genuine BT Sport app available on the Kodi platform, your Add-On breaches the applicable terms of use and will be confusing to customers, as highlighted on YouTube at https://www.youtube.com/watch?v=_UajE_wJcBc where the Add-On is described as a “BT Sports Official Kodi addon 2018” (see attached screenshot). 

> Furthermore, the unauthorised use of the BT Sport logos and screenshots from the BT Sport channels on both the Kodi and GitHub websites infringe BT’s registered and unregistered trade mark rights as well as its copyright.  

> We accept that you may previously have been unaware of your infringement of BT’s intellectual property rights or your breach of BT’s contractual terms, but now that it has been brought to your attention, please confirm that you will now stop the infringement and promptly remove both the “BT Sport Video” Add-on from Kodi’s website (and from any other website on which you have made it available) and the underlying code from GitHub, as soon as possible, and at the latest, within 7 days of receiving this email.

> Lastly, it should come as no surprise to you that BT takes the responsibility of protecting our customer details very seriously to protect against fraud and identity theft. It is of concern to us that the open source nature of your code may allow someone with malicious intent to further develop it in a way that puts our customers’ login details at risk. So for this reason and all the other reasons set-out above, we ask that you promptly remove the Add-On and underlying code from the public domain.

**Comment by enen92** [comment]
@LS80 sorry to hear. The issue was address in https://github.com/xbmc/repo-plugins/pull/1892. We need to mark the addon as broken first (with a higher addon version) before completely removing from the repository. Users will receive a notification regarding the addon being broken with an option to disable it from the system. Let us know if you need further help.
