### ISSUE TITLE
Unban Dimitrogology repository

### ISSUE THREAD

**Issue by cibic89** [xbmc/repo-plugins#1917]
### Add-on details:

- **General**
  - Add-on name: AliveGR
  - Add-on ID: 
  - Version number: 1.7.11
  - Kodi/repository version: 1.1

- **Code location**
  - URL: https://github.com/Twilight0/repo.twilight0
  - Revision/tag: 035894a
  - Branch: master

### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

The repository for this add-ons has been added to blacklist without a good reason. Please unban as this is a great collection of addons!

**Comment by cibic89** [comment]
The repository for this add-ons has been added to blacklist without a good reason. Please unban as this is a great collection of addons!

**Comment by enen92** [comment]
See comment in https://github.com/xbmc/repo-plugins/pull/1912
