### ISSUE TITLE
[Delete] plugin.video.jwtv-unofficial

### ISSUE THREAD

**Issue by ca0abinary** [xbmc/repo-plugins#1972]
### Add-on details:
- **General**
  - Add-on name: jwtv-unofficial
  - Add-on ID: plugin.video.jwtv-unofficial
  - Version number: 1.8.3
  - Kodi/repository version: helix

- **Code location**
  - URL: https://github.com/ca0abinary/plugin.video.jwtv-unofficial
  - Revision/tag: 1.8.3.1
  - Branch: master

### Description of changes:
Plugin provides content without express permission of the content publisher. As the author I would like to adhere to the wishes of the publisher set out in the [w18 4/1 Questions from Readers](
https://wol.jw.org/en/wol/d/r1/lp-e/2018364).

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by enen92** [comment]
@ca0abinary was this a takedown requested by jwtv or is it your own personal decision based on the terms of service posted above? If it was requested please also send an email to legal@kodi.tv

**Comment by ca0abinary** [comment]
This was my personal decision based on the linked information. Thanks for verifying!

**Comment by enen92** [comment]
Thanks for clarifying, addon marked as broken

**Comment by allejok96** [comment]
I respect your decision @ca0abinary. Just wanted to give you a heads up. To my big surprise the JW addon was removed from my Kodi box this morning. Or was it deactivated I didn't look? I've reinstalled it now... It was a bit unexpected and unannounced change. Would have been nicer to just get a banner saying nei when opening the app. But that's just my personal oppinion...

I can understand your concerns. I've been thinking of how the JW logo shouldn't be there as it is a trademark. Should probably remove it. But as far as the addon.... The terms for the website states:

> Create for distribution purposes, any software applications, tools, or techniques that are specifically made to collect, copy, download, extract, harvest, or scrape data, HTML, images, or text from this site. (This does not prohibit the distribution of free, non-commercial applications designed to download electronic files such as EPUB, PDF, MP3, and MP4 files from public areas of this site.)

The media from Broadcasting is not posted anywhere. It is fetched from the official servers. There is no commenting going on. The addon is simply a tool to parse and playback the media. As you can see this is explicitly allowed for non-commercial applications in JW.org's terms of service.

As I see the addon is more like a browser than a site. Still... the addon COULD be hacked to fetch media from another site... So there is that... But so could a browser... We'd have to keep check. But that's a bit of a high odds isn't it?

This is just my view. I hope at least you find it informative. If you stand by your decision... I don't know.... I may fork and re-upload... Maybe... At least keep it alive on github so people can get their hands on it if they want. Not make it too easy. Since it's not official after all...

But I've had great joy from it and just recently someone came to me and wanted help to get it on their TV too and they had bought a Pi. So I see there is interest and it brings so much to people. If the organization were to say NOPE I would be fine with it and be quiet. But as I see it, they have explicitly made an exception for this in the terms. Not many other sites does this...

It's a bit of a grey zone... It's a shame you can't trust everyone in the world.

**Comment by keithah** [comment]
So my suggestion: someone attempt to reach out to JW and seek permission. Explain to them Kodi is software that turns any PC into a Roku like experience and you've developed a 3rd party addon and wish to have it available for all to use. 

Feel free to CC me (Keith at Kodi.tv) for 'official representation' from the org. I usually handle these type of things but it'd be nice for initial ask to come from the dev. 

Thanks for developing a great addon and I hope JW sees it that way as well!

**Comment by ca0abinary** [comment]
@allejok96 I understand your concerns and did quite a bit of soul-searching before coming to this decision.  My reasons for removing this add-on are as follows:

- My reasons related to the [Questions from Readers](https://wol.jw.org/en/wol/d/r1/lp-e/2018364) article:
  - **All the material on our websites is copyrighted.**
    - I designed the logo to have a similar appearance but it is not a direct copy, this is likely still not a valid (or legal) use case.
    - Otherwise no copyrighted material appears in this code base.
  - **Downloading our publications from anywhere but jw.org is potentially dangerous.**
    - If something were to happen to the code base and inappropriate content slipped in, I would feel horrible and would not be above reproach since this warning had been issued.
    - Recently many GitHub code bases have been taken over and content altered in this manner, I don't have the time or resources to dedicate to preventing that outcome entirely (although I do take precautions such as 2FA and commit signing)
  - **Downloading our publications from anywhere but jw.org is potentially dangerous.**
    - In this section approved content access applications are listed, and mine does not fall in that list, it has the potential to be altered
  - **Directing people to jw.org helps to spread the “good news.”**
    - While true that the add-on acts as a kind of browser, it is not approved nor does it direct folks to [jw.org](https://www.jw.org)
    - Additionally I do not receive any notification when an API update is made (as this is a private API) which has had the real-world result of unreleased convention videos being shown prematurely. While this hasn't caused an issue it does highlight the problem that when improvements are made my add-on does not provide "food at the right time".
- My personal reasons:
  - Time
    - My personal time is at a premium and while there isn't much work involved in the upkeep of this add-on I've realized that even that small amount of time is too much to ask.
  - Value
    - This add-on was created during a time when the only devices capable of accessing JW Broadcasting were browsers and the Roku line of devices. At this time nearly every popular home streaming device has an official JW Broadcasting app (Amazon, Roku, Apple TV, Google TV) and are all available rather cheaply.
  - Respect
    - Many of our brothers and sisters can now obtain an official copy of the JW Broadcasting app on the streamer of their choice via official channels.
    - I respect the many hours of work done to provide and update those apps.
    - I respect my brothers and sisters who view JW Broadcasting and wish for them to get the best possible experience when viewing JW Broadcasting.
    - I respect the proper channels of getting the broadcast videos (perhaps more so than when this was first published)
  - Lifetime
    - As mentioned a few times above, I feel for various reasons (availability of official apps, wishes of the content publisher, my changing personal circumstances, etc.) that the natural lifespan of this add-on has completed. It served a purpose when it was needed and now can be retired.
    - This happens frequently in different ways where a "patch" is available until the "real deal" is released. In the past PDAs would get copies of `JW Library` materials copied from the CD, there were many placeholder solutions for Sign Language, all of these have been replaced by official applications.

It's true that some are using this add-on with experimental hardware at home. Usually those folks also have one of the other streamers as well and can switch easily. Some have used Raspberry Pi units in Kingdom Halls or homes of elderly ones, to these I am sorry that the removal of this add-on will cause trouble. The official apps and streamers have much larger technical teams behind them and can provide a much better, stable, and supported interface than what I have built.

When this add-on was initially developed it was distributed as a `zip` file before being submitted to the Kodi official repository. It is not my wish to go back in that direction and I will be deleting my GitHub repository as well.

As the code has been publicly available for some time we all know that nothing on the internet truly "dies" I'm sure copies will circulate for some time. If someone finding this code decides to resurrect the project / add-on I would ask that they strongly consider what they are doing, ask for permission, and remove my name from the code. ([g17 #4 "A Good Name is Better Than Great Wealth"](https://wol.jw.org/en/wol/d/r1/lp-e/102017127))

**Comment by allejok96** [comment]
Thanks for your quick and comprehensive response. I better understand you now. I won't do any effort to keep this addon alive, although I'll keep a personal copy ;)

I didn't realize how many devices there is that support official versions of the JW Broadcasting app. Too bad we have no Roku or Amazon boxes in Sweden though. The devices are still pretty expensive, but hey so is a decent tablet.

**Comment by martinmoerk** [comment]
Hi Jonathan,
While I fully respect your decision to take down the unofficial Kodi plugin, I think you might have misunderstood both the text and the intent on the 'terms and conditions' section from the jw,org site.
There are also some arguments you might have overlooked, and I think you should consider.
As an elder, I would prefer to have this conversation more privately though, and want to ask if we can communicate more directly somehow ...
/Martin

**Comment by allejok96** [comment]
I sent a letter to the branch office in Scandinavia asking about this. This is from my letter, translated to English:

> I have for a while benefited from an "add-on" (or "app" if you wish) for Kodi* to watch JW Broadcasting on my TV. But now the brother who developed this add-on decided to quit and totally remove it from the internet. The brother base his decision on w18.04 page 30-31.
>
> * (Kodi media center is a free and open program that can be installed on everything from $30 computers, to phones, to game consoles, and makes them work similar to an Apple TV.)
>
> *(And I list some of the reasons, like not being able to "keep up" with the changes made by the organization, not being able to leverage top notch quality, not being able to guarantee that no hacker takes control over it and so on...)*
>
> While I fully respect his decision, I want to make sure I don't break any rules or policies, since, as I said earlier, I've developed some similar programs myself. Because as I see it, a program that makes it possible to download or stream media from the website is allowed according to the ToS: *(Quote from the ToS)*. As long as the program does not claim to be from the organization, or misuses the JW logo, of course.
>
> The brother removed his add-on from the "app store", and I don't intend to re-upload it. Just the fact that there is an JW Broadcasting add-on in the app store in Kodi may confuse some, whether it is an official app or not. Considering that "distribution of free and non-commercial program" is allowed, I could see myself maintaining this program and making it available for download from a site on the internet, so technically minded people could still benefit from it. Naturally I'd never misuse any trademarks or break any copyright. I'd make it clear that the program is not from the organization, that it is used on your own risk and so on, and I'd urge people to read the Watchtower article above and make their own decision before using my program. I would not allow comments or discussions.
>
> What I cannot do (like the previous brother) is guarantee that it works 100%. I can't guarantee that no one will hack me or the program, either. That is impossible for a single person to do.
>
>So how far can I go?
>
> It's a matter of discretion. The principles in the watchtower article vs the purely legal aspect in the ToS. It would be reassuring to get a second opinion from you who knows more and have created the ToS.

And here is the very brief response I got today:

> _Käre broder [Firstname Lastname]
> Tack för ditt brev av den 6 augusti 2018.
> Baserat på informationen i ditt brev, är det lagligt att använda JW Broadcasting som du beskriver.
> Med broderliga hälsningar.
> Jehovas vittnen
> Avdelningskontoret i Skandinavien_

In English, the one sentence answer is:

> "Based on the information in your letter, it is legal to use JW Broadcasting as you describe."

So there you have it folks. At least the purely legal answer is Yes.

I will do as I said in the letter and keep the add-on in a GH repo. I will also do as you wish, Jonathan, and (try) to remove all traces of you in the code. That is ok to do, right? As long as the code maintains the same license, right? Ugh, licenses are a mess.

**Comment by ca0abinary** [comment]
@allejok96 It looks like from a legal perspective in Scandinavia you are okay. It might be worthwhile to also write the service department to ensure there's no problem from an organizational perspective. From a licensing perspective AFAIK you only need to keep it Apache licensed and attribute if you do not modify the source file licensed (i.e.: `addon.py`). So provided you make even some minor change to the functionality you can re-license it. [3. Is the Apache considered copyleft?](https://resources.whitesourcesoftware.com/blog-whitesource/top-10-apache-license-questions-answered) but I'm not a lawyer, so take any legal advise from me with a giant grain of salt. However I have no plans to prosecute, especially internationally. 😄
