### ISSUE TITLE
[context.copytostorage] v1.0.0

### ISSUE THREAD

**Issue by AbelTesfaye** [xbmc/repo-plugins#1993]
### Add-on details:

- **General**
  - Add-on name: Copy To Storage
  - Add-on ID: context.copytostorage
  - Version number: 1.0.0
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/AbelTesfaye/context.copytostorage
  - Revision/tag: 952d7cd
  - Branch: master

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by enen92** [comment]
Hey @AbelTesfaye please open the issue in xbmc/repo-scripts instead as this addon is not a plugin. It would be nice if you could submit it via a pull request but the issue is fine.

**Comment by AbelTesfaye** [comment]
Sorry about that, I thought this was the place to submit add-ons. 
Thanks anyways.
