### ISSUE TITLE
Smithsonian Addon broken

### ISSUE THREAD

**Issue by oat227** [xbmc/repo-plugins#2074]
### Add-on details:

- **General**
  - Add-on name: Smithsonian Channel
  - Add-on ID:
  - Version number: 3.02
  - Kodi/repository version: 3.11 Leia

- **Code location**
  - URL:
  - Revision/tag: 
  - Branch:

### Description of changes:

I think there has been changes to the Smithonian Channel site itself and their content is no longer freely available.
The addon therefore no longer functions and display the swirly loop indefinitely, In Windows 10 only a crash exit is the way out.
This addon is currently within the KODI repository.

### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by Rechi** [comment]
@learningit will you update your add-on?

**Comment by learningit** [comment]
Yeah. It's a simple fix that I'll get to next week.
