### ISSUE TITLE
There is a difference in description of a pull request, The commit message is with or without "v"

### ISSUE THREAD

**Issue by Opvolger** [xbmc/repo-plugins#2149]
There is a difference in description of a pull request.
The commit message is with or without "v"

* repo-plugins/PULL_REQUEST_TEMPLATE.md:
Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

* repo-plugins/CONTRIBUTING.md:
Commit your changes in a single commit, or your pull request is unlikely to be merged into the main repository.
Use git's interactive rebase feature to tidy up your commits before making them public. The commit for your add-on should have the following naming convention as the following example:
[metadata.themoviedb.org] 3.0.0

**Comment by enen92** [comment]
Nice catch we'll update the docs soon. Thanks for reporting.
