### ISSUE TITLE
[Add] plugin.video.dcmtv

### ISSUE THREAD

**Issue by therezacuet** [xbmc/repo-plugins#2313]
### Add-on details:
  - Add-on name: DCM TV
  - Add-on ID:plugin.video.dcmtv
  - Version number:1.0.0
  - Kodi/repository version: Leia
  - URL:https://github.com/therezacuet/kodi-tv-youtube-channel-ad-on
  - Revision/tag: 2b2c819
  - Branch:master

**Comment by Rechi** [comment]
@therezacuet can you open a Pull Request? It makes reviewing your code easier.
