### ISSUE TITLE
[Broken]- Loyalty Books

### ISSUE THREAD

**Issue by KarellenX** [xbmc/repo-plugins#2355]
### Add-on details:

- **General**
  - Add-on name: **Add-on:Loyal Books**
  - Add-on ID: 
  - Version number: **v1.0.8**
  - Kodi/repository version: **Isengard thru Leia**

### Description of changes:
**Add-on is broken in v17 and v18**

Wiki... https://kodi.wiki/view/Add-on:Loyal_Books
Kodi.tv... https://kodi.tv/addon/music-add-ons-plugins/loyal-books
Forum... https://forum.kodi.tv/showthread.php?tid=242478
https://github.com/xbmc/repo-plugins/tree/gotham/plugin.audio.booksshouldbefree

**Comment by KarellenX** [comment]
@Rechi 

Thanks for the fix and move.

Is it possible to add a "Broken" label to github?

**Comment by enen92** [comment]
@KarellenX done for the label. Will take care of the addon soon.
