### ISSUE TITLE
[wiki] plugin.audio.soundcloud

### ISSUE THREAD

**Issue by jaylinski** [xbmc/repo-plugins#2416]
### Add-on details:

- **General**
  - Add-on name: SoundCloud
  - Add-on ID: plugin.audio.soundcloud
  - Version number: 3.0.0
  - Kodi/repository version: Krypton v17

- **Code location**
  - URL: https://github.com/jaylinski/kodi-addon-soundcloud
  - Revision/tag: v3.0.0

### Description of issues:

It seems the wiki-addon-bot didn't update the wiki after the new 3.0.0 version got released:
https://kodi.wiki/view/Add-on:SoundCloud

Is this a known issue? I actually wanted to report this to https://github.com/xbmc/xbmc.wiki.bot, but issues are deactivated in this repo.

**Comment by Rechi** [comment]
What isn't updated?

**Comment by jaylinski** [comment]
@Rechi the problem has solved itself. (https://kodi.wiki/index.php?title=Add-on%3ASoundCloud&type=revision&diff=171829&oldid=170204)

Seems I should have been more patient.
