### ISSUE TITLE
Pull request guide?

### ISSUE THREAD

**Issue by leopheard** [xbmc/repo-plugins#2423]
So I have read pretty much the only thing I can find online about submitting an official addon at this [https://kodi.wiki/view/Submitting_Add-ons](url) and it still doesn't tell me how to submit a pull request properly. 

I have tried but it wants me to compare all sorts of other versions of Kodi and I can't work out how to submit my addon? Any help would be greatly appreciated

**Comment by remichie** [comment]
All info is very vague and outdated with many dead links, and not a lot of help from members of team Kodi!

**Comment by skipmodea1** [comment]
For making a PR i made a bat file i call.

I call the bat file this f.e.:
makepr-anyaddon.bat skipmodea1 leia plugin.video.gamekings 1.2.14

makepr-anyaddon.bat:

@echo off
if "%1"=="" goto usage
if "%2"=="" goto usage
if "%3"=="" goto usage
if "%4"=="" goto usage

@echo on
rem For a total restart: Delete repo-plugins from your repo on Github: go to this page https://github.com/%1/repo-plugins and click settings and scroll to the bottom of this page and enter the name of the repo and click the red button 
rem For a total restart: Fork the official kodi repo to your repo on Github: goto this page https://github.com/xbmc/repo-plugins and click on the fork button
rem Deleting C:\Kodi_fork\repo-plugins and Cloning the kodi repo from your github to your pc
rem Ctrl-C to abort!!!!
pause
rmdir /s /q C:\Kodi_fork\repo-plugins
timeout 1
rmdir /s /q C:\Kodi_fork\repo-plugins
cd C:\Kodi_fork\
c:
rem Cloning the kodi repo from your github to your pc
git clone git@github.com:%1/repo-plugins.git repo-plugins
cd C:\Kodi_fork\repo-plugins
rem Assign the official kodi repo to a remote called "upstream"
git remote add upstream https://github.com/xbmc/repo-plugins.git
rem Add the addon in your github as a remote
git remote add %3 git@github.com:%1/%3
rem Fetch your addon from your github
git fetch %3
rem Make a branch for your addon and go to that branch
git checkout -b b-%3-%4 %3/master
rem go to the %2 branch
git checkout %2
rem delete the old version of the addon
git rm .\%3\ -r
rem get the new version of the addon from the branch you created 
git read-tree --prefix=%3/ -u b-%3-%4
rem force remove .git files
git rm -f C:\Kodi_fork\repo-plugins\%3\.gitattributes
git rm -f C:\Kodi_fork\repo-plugins\%3\.gitignore
rem show the differences (press esc and then q to exit)
git diff --staged
rem Commit the changes
Git commit -m "[%3] %4"
rem push the stuff to the %2 branch in your github (if everything went ok): git push origin %2
rem after that go to repo-plugins in your github and go to the %2 branch and make a pull request
@echo off
exit /B 1

:usage
@echo A parameter is missing
@echo Usage: %0 ^<Your Github Username (f.e. leetcoderbob)^> ^<Name of the Kodi Version (f.e. gotham)^> ^<Full Addon Name (f.e. plugin.video.youtube)^> ^<Addon Version (f.e. 1.1.4)^>
exit /B 1

**Comment by FraserChapman** [comment]
> So I have read pretty much the only thing I can find online about submitting an official addon at this [https://kodi.wiki/view/Submitting_Add-ons](url) and it still doesn't tell me how to submit a pull request properly.
> 
> I have tried but it wants me to compare all sorts of other versions of Kodi and I can't work out how to submit my addon? Any help would be greatly appreciated

---

> All info is very vague and outdated with many dead links, and not a lot of help from members of team Kodi!

----

There is a complete step-by-step guide here: https://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging

Also a guide to updating an existing PR here:
https://kodi.wiki/view/HOW-TO:Update_a_pull_request_to_an_official_addon_repository_on_GitHub

**Comment by leopheard** [comment]
> @FraserChapman 
> 
> There is a complete step-by-step guide here: https://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging

That guide has an error in the very first step

**Comment by FraserChapman** [comment]
@leopheard 

> That guide has an error in the very first step

How so? Do you mean that "me" isn't the name for *your* github account!?
Fork the repo and check it out - how is there any error in that? I followed it for my first add-on without any problem...

**Comment by skipmodea1** [comment]
I can see how the first step is confusing for people that are new to git. I would split it in separate  steps:

- Login in to your github account (make one if you don't have one yet): https://github.com
- Fork the relevant official add-on repository by click on the Fork icon here: https://github.com/xbmc/repo-plugins 
- Clone the reletevant official etc etc.

**Comment by leopheard** [comment]
> I can see how the first step is confusing for people that are new to git. I would split it in separate steps:
> 
> * Login in to your github account (make one if you don't have one yet): https://github.com
> * Fork the relevant official add-on repository by clicking on the Fork icon here: https://github.com/xbmc/repo-plugins
> * Clone the reletevant official etc etc.

I have closed the plugins repo, but how do I add my addon into a pull request? I've gone to xbmc/repo-plugins and clicked 'New pull request', but it's not clear where I merge my edits from. I've followed this guide already: [https://kodi.wiki/view/HOW-TO:Create_add-on_PRs_using_Git_Subtree_Merging](url)

**Comment by leopheard** [comment]
After running **git push origin plugin.audio.theinterceptpodcast** it shows a pull request is possible but when I click on it, it's saying not possible:

[](https://www.dropbox.com/s/xxoikom4vk7tjsx/1111.png?dl=0)

**Comment by FraserChapman** [comment]
Change the "base" from "master" to "Leia" on the drop down (in your pic). I.e. the branch you are submitting to. I'd also suggest maybe reading a book/website on git basics or just setting up your own repo to play with so you at least understand the basics...

**Comment by leopheard** [comment]
> Change the "base" from "master" to "Leia" on the drop down (in your pic). I.e. the branch you are submitting to. I'd also suggest maybe reading a book/website on git basics or just setting up your own repo to play with so you at least understand the basics...

So I tried that:

https://www.dropbox.com/s/nttwqgsy1fk746n/Screenshot%20from%202019-09-01%2020-35-36.png?dl=0

Still confused

**Comment by FraserChapman** [comment]
You shouldn't be merging or pulling anything. The steps in the guide are pretty simple - which is why I posted the link to it. Honestly I'm not sure I can do to help you other than suggesting you learn git. Sorry...
