### ISSUE TITLE
[Broken] plugin.video.glwiz

### ISSUE THREAD

**Issue by bbk79** [xbmc/repo-plugins#2432]
### Add-on details:

- **General**
  - Add-on name: GLWiZ
  - Add-on ID: plugin.video.glwiz
  - Version number: 1.1.3
  - Kodi/repository version: Krypton Leia Matrix

### Description of changes:

I'm the author and I just noticed this add-on has been broken for a while and it's unlikely that I get a chance to work on a fix. Looking in the Wiki, I couldn't find the process for marking the add-on as broken or better just removing it from the official repository, can you please help? Should I submit a PR?

**Comment by Rechi** [comment]
@bbk79 see https://kodi.wiki/view/Addon.xml#.3Cbroken.3E

**Comment by bbk79** [comment]
Thanks @Rechi 
https://github.com/xbmc/repo-plugins/pull/2441
