### ISSUE TITLE
[Add] plugin plugin.audio.criminalpodcast

### ISSUE THREAD

**Issue by leopheard** [xbmc/repo-plugins#2445]
Sorry I couldn't issue a pull request, I have no idea how to do one after a lot of trying and there are no guides on how to do it.

### Add-on details:

- **General**
  - Add-on name: Criminal Podcast
  - Add-on ID: plugin.audio.criminalpodcast
  - Version number: 1.0
  - Kodi/repository version: 18.0 Leia

- **Code location**
  - URL: https://github.com/leopheard/criminalpodcast
  - Revision/tag:  c1a29d5
  - Branch: master

### Description of changes:

Audio addon to provide streaming for a podcast

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by enen92** [comment]
@leopheard track the review here: https://github.com/xbmc/repo-plugins/pull/2463

**Comment by leopheard** [comment]
No particularly sure what to do with this. I can't use xmbcswift2 anymore because it's python2 and therefore my plugin routing is now gone, and finding any info on what to use instead is proving fruitless online

**Comment by enen92** [comment]
See https://github.com/tamland/kodi-plugin-routing
What do you want to do regarding this plugin? Are you going to handle the PR yourself? If so I can close mine and this issue too.

**Comment by leopheard** [comment]
I've not managed to do a proper PR yet, I did a few yesterday and different addons kept overwriting into the same PR. So yeah might be worth keeping this open and then hopefully later I'll find out how to do a proper PR request

**Comment by leopheard** [comment]
> See https://github.com/tamland/kodi-plugin-routing
Are there any further guides for the above routing addon? I can't translate my current addon into this new format because there is no guide for, I'm just taking guesses in the dark e.g. I've replaced get_string in my menu section to make label': plugin.ListItem(30001), but it's telling me it needs to be unicode? This is so frustrating

**Comment by enen92** [comment]
Have a look into https://github.com/xbmc/generator-kodi-addon. Our tutorial addons make use of the routing script.module.

**Comment by leopheard** [comment]
> Have a look into https://github.com/xbmc/generator-kodi-addon. Our tutorial addons make use of the routing script.module.

Should that addon be installable? I've tried installing that .zip but it's not installable. I've also looked at the scripts.module addon and there's a few examples listed but no explanation how they work and only limited ones. I just need a proper guide to see how to do it, but there's nothing available

**Comment by Razzeee** [comment]
You need to install the generater via npm, then you can create a project via commandline. If you zip up those files, they should be installable. Or push them to github and let github create the zip for you.

**Comment by enen92** [comment]
Stalled for too long. I'm closing the PR.
