### ISSUE TITLE
[Update] plugin.program.newgrounds

### ISSUE THREAD

**Issue by erfg12** [xbmc/repo-plugins#2560]
### Add-on details:
- **General**
  - Add-on name: Newgrounds
  - Add-on ID: newgrounds
  - Version number: 1.0.5
  - Kodi/repository version: Leia
- **Code location**
  - URL: https://github.com/erfg12/kodi-repo/tree/master/plugin.program.newgrounds
  - Revision/tag: c7dee26a70606bea20d9d83efbb7b69db29f2385
  - Branch: Master
### Description of changes:
Changed cURL to JSON API

**Comment by basrieter** [comment]
You will need to create PR for your add-on.
