### ISSUE TITLE
[Update] plugin.program.newgrounds

### ISSUE THREAD

**Issue by erfg12** [xbmc/repo-plugins#2565]
# Add-on details:
- **General**
  - Add-on name: plugin.programs.newgrounds
  - Add-on ID: newgrounds
  - Version number: 1.0.5
  - Kodi/repository version: Leia
- **Code location**
  - URL: https://github.com/erfg12/kodi-repo/tree/master/plugin.program.newgrounds
  - Revision/tag: b47607669628c7d9b365f99a4f18fa37dc7c0a6f
  - Branch: Master

### Description of changes:
- Changed from cURL to JSON API

**Comment by jaylinski** [comment]
You have to create a pull request. https://kodi.wiki/view/Submitting_Add-ons

**Comment by basrieter** [comment]
If this is still a valid update, please submit a PR to the correct repo and branch in order to get this update merged.

**Comment by erfg12** [comment]
Sorry, I'm just tired of this. I updated my plugin, and I'm told to go even further every time it's always something new. So I'm done. Remove the plugin and I'll have a private repo for the people who still want to use it.
