### ISSUE TITLE
Swedish tv4play has brook down I hope it will be fixed😀

### ISSUE THREAD

**Issue by cabban** [xbmc/repo-plugins#2567]
### Add-on details:

- **General**
  - Add-on name: retrospect
  - Add-on ID:
  - Version number: 18.4
  - Kodi/repository version: 5.07

- **Code location**
  - URL:
  - Revision/tag: 
  - Branch:

### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by enen92** [comment]
@basrieter this is related to retrospect. Please close if doesn't apply.
@cabban please bring similar issues to the upstream location of the addon: https://github.com/retrospect-addon/plugin.video.retrospect

**Comment by basrieter** [comment]
Please create an issue in the Retrospect repository issue tracker: https://github.com/retrospect-addon/plugin.video.retrospect/issues

Please also attach a debug retrospect.log to that new issue and give e clear description of what is not working.
