### ISSUE TITLE
LiveLeak plugin broken due to website closed

### ISSUE THREAD

**Issue by Botster** [xbmc/repo-plugins#3591]
### Add-on details:

- Add-on name: LiveLeak
- Add-on ID: plugin.video.liveleak
- Version number: 1.4.2 & 2.0.0
- Kodi/repository version: Jarvis & Matrix, respectively

### Ownership
- [X] I am the owner of this add-on

    
### Broken because:

The website it was scraping, https://liveleak.com, has closed redirecting to a new site: https://www.itemfix.com/?r=ll

Also reference:
https://mashable.com/article/liveleak-dead-shut-down/

IMO, both versions of the plugin, in their respective branches, should be removed.

**Comment by ronie** [comment]
thanx for the heads-up!

addon has been marked broken:
https://github.com/xbmc/repo-plugins/commit/f38d56aa86ed97b279b1b4a4a148ac9860228b13
https://github.com/xbmc/repo-plugins/commit/19b8b247b04b6684b549e16c03c63cc99f10f681
