### ISSUE TITLE
Addon of La Capi TV

### ISSUE THREAD

**Issue by b4zz4** [xbmc/repo-plugins#3923]
- Add-on name: La Capi TV
 - Add-on ID: plugin.video.lacapitv
 - Version number: 1.0.0
 - Kodi/repository version: 19.4 (19.4.0) Matrix
 - Code location URL:  https://git.tuxfamily.org/4232/kodi_plugin_video_lacapitv.git/
 - Revision/tag: 
 - Branch: master

**Comment by enen92** [comment]
Please send a pull request with the code to the matrix branch of this repo, we don't accept submissions via issues anymore.

**Comment by b4zz4** [comment]
I mean, clone the repo and add my addons and send a pullrequest?
