### ISSUE TITLE
Broken: plugin.video.curiositystream - seems API changed

### ISSUE THREAD

**Issue by wa3573** [xbmc/repo-plugins#4208]
### Add-on details:

- Add-on name: Curiosity Stream
- Add-on ID: plugin.video.curiositystream
- Version number: 2.0.2+matrix.2
- Kodi/repository version: 19.4

### Ownership
- [ ] I am the owner of this add-on

    
### Broken because:

Seems the Curiosity Stream API may have changed, and I was getting some error messages. I'm too busy to include logs or every detail, but I'll share what I discovered, and how I fixed it. Hopefully this will help someone with the same issue. Or if someone really wants, I can make the changes and open a PR.

### Issue: `IndexError` because of empty streams list

Error originates from last line below (router.py):

```
    def _play_media(self, media):
        stream = self._cs_api.media_stream_info(media)
        play_item = xbmcgui.ListItem(path=stream["streams"][0]["master_playlist_url"])
```

#### Fix: Adapt to seeming API changes (curiositystream.py)
I solved this using postman to check API responses. Two problems. First, the API wasn't happy with the User-Agent provided by the Python requests package. Give it something it does like:
```

    def authenticate(self, force=False):
...
            self._session.headers.update(
                {"x-auth-token": data["message"]["auth_token"],
                "User-Agent": 'Mozilla/5.0'}
            )
```

Second, the "type" field of the response showed "HD" which (pretty sure) wont match with `== "hd"`:

```
    @_authenticate_and_retry_on_401
    def media_stream_info(self, media):
...
        return {
            "streams": [
                encoding
                for encoding in data["data"]["encodings"]
                if str(encoding["type"]).lower() == "hd"
            ],
            "subtitles": data["data"]["closed_captions"]
            if "closed_captions" in data["data"]
            else [],
        }
```

### Issue: Kodi can't play the "master_playlist_url"

Maybe the API changed the provided file from `.m3u8` to `.mpd`. Kodi seemed confused.

#### Fix: Use `inputstream.adaptive` (router.py)

```
    def _play_media(self, media):
        stream = self._cs_api.media_stream_info(media)
        play_item = xbmcgui.ListItem(path=stream["streams"][0]["master_playlist_url"])
        play_item.setSubtitles([c["file"] for c in stream["subtitles"]])
        
        play_item.setProperty('inputstream', 'inputstream.adaptive')
        play_item.setProperty('inputstream.adaptive.manifest_type', 'mpd')
        xbmcplugin.setResolvedUrl(self._plugin_handle, True, listitem=play_item)
```
A proper solution would probably check to make sure it's really an `mpd` file first, but things seem to be working consistently for me.

Hope this helps!

**Comment by mintsoft** [comment]
@GMaxera Not sure if you've seen this, I'm happy to pick up PRing this into the main repo and stuff if you don't want to do it etc

**Comment by GMaxera** [comment]
> @GMaxera Not sure if you've seen this, I'm happy to pick up PRing this into the main repo and stuff if you don't want to do it etc

No, I didn't see, I'm sorry.

If you can pick it up and fix it, please do it.
At the moment, I'm not able to develop on it, really sorry for that.

**Comment by mintsoft** [comment]
No problem, I'll probably pull it into its own repository and stuff and we can sort out getting it all consistent once it's working again

**Comment by mintsoft** [comment]
I've PR'd in a fix for it. The code for just the plugin is here: https://github.com/mintsoft/plugin.video.curiositystream

**Comment by mintsoft** [comment]
This can be closed now; the addon is fixed as of June and I've taken over as maintainer of this addon for the forseeable

**Comment by mintsoft** [comment]
@basrieter Can you close this issue for me? This was fixed in: https://github.com/xbmc/repo-plugins/pull/4400
