### ISSUE TITLE
Add-on:Missing Movies

### ISSUE THREAD

**Issue by KarellenX** [xbmc/repo-plugins#4212]
### Add-on details:

- Add-on name: **Add-on:Missing Movies**
- Add-on ID: **plugin.video.mms**
- Version number: **4.0.5**
- Kodi/repository version: 

### Ownership
- [ ] I am the owner of this add-on

### Broken because:
This addon has been considered broken since 2018... https://forum.kodi.tv/showthread.php?tid=118263&pid=2693885#pid2693885
The repo shows no updates since January 2016... https://github.com/tamland/kodi-missing-movies

For some reason the wiki bot shows it available for v18, v19 and v20. Is it possible to tell why it is showing up as available for v20? Maybe @howie-f might know?
https://kodi.wiki/view/Add-on:Missing_Movies

Please mark as broken.

**Comment by howie-f** [comment]
@KarellenX i can only suspect because the Nexus branch in https://github.com/xbmc/repo-plugins/ isnt set up properly yet..

**Comment by KarellenX** [comment]
Looks like this addon was updated back in 2020 by another user. But none of the links in the addon.xml file have been updated, so they are all pointing to old posts advising the addon is broken which flow through to the wiki and kodi.tv.

I'll close this issue as the addon has been updated for Python 3

```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="plugin.video.mms" name="Missing Movies" version="4.1.0" provider-name="takoi, juokelis">
    <requires>
        <import addon="xbmc.python" version="3.0.0"/>
        <import addon="script.module.routing" version="0.2.3+matrix.1"/>
    </requires>
    <extension point="xbmc.python.pluginsource" library="default.py">
        <provides>video</provides>
    </extension>
    <extension point="xbmc.addon.metadata">
        <summary lang="en_GB">Find missing videos</summary>
        <description lang="en_GB">Scans media sources for movies, TV shows and episodes that got missed during the library scan. This add-on can used to identify, play or manually add missing videos to your media library.</description>
        <news>
v4.1.0 (2020-04-05) by juokelis
- Ported to python 3.0 to run on v19 Matrix.

v4.0.5 (2016-01-17) by tamland
- Improved detection of bluray companion files.
        </news>
        <license>GPL-3.0-or-later</license>
        <platform>all</platform>
        <source>https://github.com/tamland/kodi-missing-movies</source>
        <forum>https://forum.kodi.tv/showthread.php?tid=118263</forum>
        <assets>
            <icon>resources/media/icon.png</icon>
            <fanart>resources/media/fanart.jpg</fanart>
        </assets>
    </extension>
</addon>
