### ISSUE TITLE
Canadian Broadcasting Corp (CBC) add-on authentication broken

### ISSUE THREAD

**Issue by greenmr** [xbmc/repo-plugins#4303]
### Add-on details:
- Add-on name: Canadian Broadcasting Corp (CBC)
- Add-on ID: plugin.video.cbc
- Version number:  4.0.15+matrix.1
- Kodi/repository version: Matrix

### Ownership
- [ ] I am the owner of this add-on

### Broken because:
I'm not sure when this started because I haven't used the add-on in a few weeks, but now I can browse shows as before but attempts to play them result in the error "Authorizatoin [sic] Failed". Reauthorizing the add-on doesn't help. Using the same login credentials with the web version of CBC Gem and the  official Gem Android app both work fine. It is just the Kodi add-on which has stopped working.

**Comment by basrieter** [comment]
Please report this at github of the add-on developer: https://github.com/micahg/plugin.video.cbc
