### ISSUE TITLE
Radio.de add is not working anymore

### ISSUE THREAD

**Issue by georgkrause** [xbmc/repo-plugins#4568]
### Add-on details:

- Add-on name: Radio
- Add-on ID: plugin.audio.radio_de
- Version number: 3.0.9+matrix.1
- Kodi/repository version: 21/3.4.0

### Ownership
- [ ] I am the owner of this add-on

    
### Broken because:

Whatever action I want to take in the addon, there is a network error. I think the radio.de API changes and the changes are not yet reflected in the repository.

I am not aware if thats the right ways to report such issue.  In the addon-repository the malfunction is already reported, see https://github.com/XBMC-Addons/plugin.audio.radio_de/issues/61 or https://github.com/XBMC-Addons/plugin.audio.radio_de/issues/59 . However, no action is taken. I'd suggest to remove the addon from the official repository until its fixed.

If you are aware of any maintainer of the addon, I might be interested in helping getting the plugin running again. Let me know if there is a way to get involved.

**Comment by basrieter** [comment]
The right place to report this, is at the source repository of the add-on. Not here.

**Comment by georgkrause** [comment]
@basrieter I report it here because as I mentioned, its already reported in the source repository. But this belongs to the same org as the index, however, nobody replies there. As I already wrote in the issue, I am asking you to remove a non-functional addon from the repository to avoid people getting annoyed by installing a broken plugin.

**Comment by georgkrause** [comment]
@basrieter I am especially wondering why there is a category to report broken addons if you don't want those issues to be opened. Am I missing something?

**Comment by basrieter** [comment]
The original add-on author needs to create e PR to mark an add-on as `broken`, if and only if he/she does not intent to fix it. A broken add-on will be removed on all Kodi installs.

Only of the owner is unknown or not active we could do this. So let's just wait for now and I will reach out to the devs in the meantime.

**Comment by georgkrause** [comment]
@basrieter Thank you for the info! I filed a PR to mark the addon as broken, before I've read your comment. Sorry if this is useless now, but I think its fair to mark the addon as broken for now.

Just so you are aware: I am planning into fixing the issue, but it might take a while.

**Comment by basrieter** [comment]
No worries, I will tag the original devs for an OK.
