### ISSUE TITLE
[Update] plugin.audio.intergalacticfm

### ISSUE THREAD

**Issue by PanderMusubi** [xbmc/repo-plugins#813]
### Add-on details:

- **General**
  - Add-on name: Intergalactic FM
  - Add-on ID: plugin.audio.intergalacticfm
  - Version number: 1.0.7
  - Kodi/repository version: isengard, jarvis and higher

- **Code location**
  - URL: https://github.com/intergalacticfm/plugin.audio.intergalacticfm
  - Revision/tag: 956a7ab
  - Branch: master

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by phate89** [comment]
Added to repo.. Thanks!
