### ISSUE TITLE
[New] plugin.video.BlanketFort

### ISSUE THREAD

**Issue by BlanketFortMedia** [xbmc/repo-plugins#828]
### Add-on details:

- **General**
  - Add-on name: Blanket Fort
  - Add-on ID: plugin.video.BlanketFort
  - Version number: 1.0.0
  - Kodi/repository version: Jarvis

- **Code location**
  - URL: https://github.com/BlanketFortMedia/plugin.video.BlanketFort
  - Revision/tag: 0c23b4a
  - Branch: master

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by learningit** [comment]
You need to read the submission doc's carefully. You need to setup a github
account and submit as a PR against the repo, not a zip. Version needs to
follow x.y.z.

**Comment by BlanketFortMedia** [comment]
Thanks for the tips. I have updated the information.

**Comment by learningit** [comment]
Sorry. please read the submission doc's carefully. You need to fork
xbmc/repo-plugins into your git, create a new branch using the correct repo
branch as a base, copy your add-on updates there and submit a pull request
from there.

**Comment by BlanketFortMedia** [comment]
My mistake. Hopefully I got it right this time.

**Comment by learningit** [comment]
Ah, so zips are OK these days? Difficult to review though.

**Comment by BlanketFortMedia** [comment]
I had read that is 3.2 Issue ticket of Submitting Add-Ons but then thought I misunderstood. This can be closed as I streamlined the plug-in and will submit via a PR.
